### PR TITLE
Feature/remove mongodict

### PR DESCRIPTION
**Pull request by flavioamieiro**
This removes MongoDict from the backend. After this is merged, we'll need to adapt pypln.web to read from mongo directly.

@fccoelho and @israelst please take a close look at this PR, since I had to make a lot of choices here. Specially on 72a54a5bad

### CODE REVIEW

**Comment by fccoelho** [comment]
For me this looks ok, apart from the few comments I've made on specific commits. As soon as all tests are passing, we can merge

**Comment by flavioamieiro** [comment]
I've added tests for Bigrams and Trigrams with dollar signs and dots. I still didn't figure out why the Bigrams worker is not affected by the same issue. 
With this, I think that this PR is ready to merge, unless we decide to follow @israelst 's (good) suggestion and replace $ and . close to the db for all workers. In any case, we should not merge this branch until pypln.web catches up.
I'll start working on pypln.web's side of things now.

**Comment by fccoelho** [comment]
I Think we should go ahead and merge it as is. 

Regarding the bigram/trigram bug mystery, I think the answer may lie within NLTK, in the way the colocationfider objects work. We shoul  run some tests in the python console and look at the output, and not only if it generates an exception or not.

**Comment by flavioamieiro** [comment]
@fccoelho I've changed the tests for bigrams and trigrams. I agree with you on that. 

I also think this is ready now but, as I said, let's leave the PR open for now. If we merge this in `develop` now, pypln.web won't be up-to-date with pypln.backend. This would mean we would not be able to deploy quickly if we needed to. I say we leave this branch here and, as soon as pypln.web is also ready, merge it.

**Comment by flavioamieiro** [comment]
@fccoelho and @israelst : for a comparison, I've created a small [benchmarking script](https://gist.github.com/flavioamieiro/cdfe6addcd24a83c2a6e) and ran it against this branch and the current develop branch. The results are pretty interesting (here they are: [with mongodict](https://gist.github.com/flavioamieiro/a04d1f0e4b97a5a70480) and [without mongodict](https://gist.github.com/flavioamieiro/89d9ea3e0f386e0bf353)). This branch is definitely faster than what we had before, not to mention the simplification of the code base.

**Comment by fccoelho** [comment]
Great results! now let's merge and run our favorite load test (the mediacloud collection) ;-)

**Pull request merged**
