### PR TITLE
Implemented basic Sphinxsearch indexer worker.

### PR DESCRIPTION
**Pull request by fccoelho**
Requires Sphinxsearch to be installed on a reachable host.

Other fields can be indexed as well, Suggestions are welcome.

### CODE REVIEW

**Comment by fccoelho** [comment]
I think this PR should be abandoned, as I don't think that indexing belong in PyPLN anymore.

Do you all agree?

**Comment by flavioamieiro** [comment]
I do. I think that, since we are focusing PyPLN more on document analysis than on corpora, indexing is out of scope, at least for now.

**Comment by fccoelho** [comment]
Change of Plans. Given the possibie establishment of indexing services through the API, let's try to finish this feature later

**Comment by fccoelho** [comment]
Abandoning this line of work

**Pull request closed without merging**
